version: '3'
services:
  db:
    image: "postgres" 
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=test
    restart: always
  node:
    build: .
    command: node dist/src/server.js
    ports:
      - "3000:3000"
    depends_on:
      - db